### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by simone-marini** [jdidion/biotools#5]
Thanks for this wonderful resource page!

I suggest to add to the multi-omics data integration list this implementation of a tri-factorization algorithm for both discovery and prediction (Matlab code: https://gitlab.com/smarini/MaDDA/), applied for grouping patient for precision oncology ("Patient similarity by joint matrix tri-factorization to identify subgroups in precision oncology", Vitali et al., Jamia OPEN, in press) and protease-target prediction (https://www.biorxiv.org/content/early/2018/03/03/275024).

**Comment by jdidion** [comment]
Thanks Simone! Feel free to add this to the list via a pull request. I will approve it.
